AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC Interface Endpoint for AWS Transfer Family

Parameters:
  ProjectName:
    Type: String
    Description: Project name or prefix for tagging.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the endpoint will be created.

  SubnetIds:
    Type: CommaDelimitedList
    Description: List of subnet IDs where the endpoint will be deployed.

  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: List of security group IDs to associate with the endpoint.

Resources:
  TransferVpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: "com.amazonaws.ap-southeast-1.transfer.server"
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: !Ref SecurityGroupIds
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-transfer-vpc-endpoint"

Outputs:
  TransferVpcEndpointId:
    Description: ID of the created VPC Interface Endpoint for AWS Transfer Family
    Value: !Ref TransferVpcEndpoint
    Export:
      Name: !Sub "${ProjectName}-TransferVpcEndpointId"
